server:
  port: 8097

spring:
  application:
    name: gate
  cloud:
    inetutils:
      preferredNetworks:
        - 192.168
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: roger
          uri: ws://123.57.200.185:8097
          predicates:
            - Path=/iot/roger